### ISSUE TITLE
Swift throws "Use of undeclared type 'Note' " Error

### ISSUE THREAD

**Issue by nimarez** [aws-samples/aws-mobile-ios-notes-tutorial#1]
`var _fetchedResultsController: NSFetchedResultsController<Note>? = nil`

Note is not referenced before, so the compiler cannot resolve it.

**Comment by dmennis** [comment]
Nim104. We have completely refactored the starter app and it no longer uses the NSFetchedResultsController and Core Data has been removed. Please download or clone the latest and let us know if you have any issues.
